{{- if and (eq (include "dell-bios.shouldRenderVictoriaMetrics" .) "true") (eq .Values.monitoring.scrapeType "pod") }}
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: {{ include "dell-bios.fullname" . }}
  labels:
    {{- include "dell-bios.labels" . | nindent 4 }}
    {{- with .Values.monitoring.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "dell-bios.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  podMetricsEndpoints:
    - port: metrics
      interval: {{ .Values.monitoring.interval }}
      scrapeTimeout: {{ .Values.monitoring.scrapeTimeout }}
      {{- if or .Values.clusterLabel.enabled .Values.monitoring.relabelings }}
      relabelConfigs:
        {{- if .Values.clusterLabel.enabled }}
        - targetLabel: cluster
          replacement: {{ .Values.clusterLabel.value | quote }}
        {{- end }}
        {{- with .Values.monitoring.relabelings }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- with .Values.monitoring.metricRelabelings }}
      metricRelabelConfigs:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
