{{- if and .Values.alerts.enabled (eq (include "dell-bios.shouldRenderVictoriaMetrics" .) "true") }}
{{- if .Capabilities.APIVersions.Has "operator.victoriametrics.com/v1beta1" }}
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: {{ include "dell-bios.fullname" . }}
  labels:
    {{- include "dell-bios.labels" . | nindent 4 }}
    {{- with .Values.alerts.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- include "dell-bios.alertGroups" . | nindent 2 }}
{{- end }}
{{- end }}
